name: python checks
on: pull_request
jobs:
  bandit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/bandit-check@main
        with:
          path: "."
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          pip install black==22.12.0
      - run: |
          black --check --line-length=79 --verbose .
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          pip install flake8==5.0.4
      - run: |
          flake8 --verbose .
  isort:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          pip install isort==5.11.4
      - run: |
          ls -la
          isort --profile black --check-only .      
  unit-tests:
    runs-on: ubuntu-20.04
    needs: [isort, flake8, black, bandit]
    steps:
      - uses: actions/checkout@v2
      - run: |
          python -m pip install --upgrade pip
          pip install poetry==1.5.1
          poetry install
      - run: |
          python -m pytest .      
