name: python checks
on: pull_request
jobs:
  bandit:
    runs-on: ubuntu-20.04
    steps:
      - uses: jpetrucciani/bandit-check@main
        with:
          path: "."
  black:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          python -m pip install --upgrade pip
          pip install black==22.12.0
      - run: |
          black --check --line-length=79 --verbose .
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          python -m pip install --upgrade pip
          pip install flake8==5.0.4
      - run: |
          flake8 --verbose .
  isort:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          python -m pip install --upgrade pip
          pip install isort==5.11.4
      - run: |
          ls -la
          isort --profile black --check-only .      
  unit-tests:
    # This check should be adjusted, mounting the code base
    # into the container, do poetry install and running the tests.
    runs-on: ubuntu-20.04
    needs: [isort, flake8, black, bandit]
    steps:
      - run: |
          python -m pip install --upgrade pip
          pip install openpyxl==3.1.2
          pip install pytest==7.4.2
          pip install openpyxl-stubs==0.1.25
      - run: |
          python -m pytest .      
